### ISSUE TITLE
missing secret.properties

### ISSUE THREAD

**Issue by pfk-beta** [netguru/baby-monitor-client-android#388]
* What went wrong:
A problem occurred evaluating script.
> File /home/frankowp/KOD/others/baby-monitor-client-android/secret.properties not found

**Comment by pauledwardtang** [comment]
@pfk-beta this looks intentional because it's ignored via `.gitignore`. It's generally considered a bad practice to leak any secrets into your repository, so this makes sense. The `google-services.json` isn't checked in either so you'll also need to provide one to get past this issue.

I can't compile or run this project without the changes from #392, but when I created the following `secrets.properties` file, this particular problem went away.

```
FirebaseCloudMessagingServerKey=ASDF;
```

**Comment by pfk-beta** [comment]
Thanks for your time. I think I have solved problem by workaround
